package com.nationdev.shopapp.sampledata

import com.nationdev.shopapp.model.Product
import java.math.BigDecimal
val sampleHeros = listOf(
    Product(
        name = "The Witcher de Henry Cavill",
        price = BigDecimal("130.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV85ZMn6QzT-JZc4tQtzcBdwCMve11b55MENdvT5WTYdplx2qzlCVhVVPYGy5bwq5wgpqbnD37_6TDvtvItMTs4cXSPiRC4DXFIsJTry0-Q6npdX1Q2yBRS0oyPDjbAtEEtZFfzHPLlTpo2IE2tpML58DnbuFPuPkHuHVgB0Bzso_bolVBkeajSYEG_1f8uIa7BARQZvLY45soN18W2srT8KcXA9TTXHi4MfO-b7lvw59jQf7avXZWk4IuJ2ZPTF7C_lUHuvze74ECiC1mWcRWbuYdwmM9YWJr-nPysebsbodHXNl7lVVga1Y98wIuP-G147mKkkWANMvZF4fG-MrhU1vif40dnamcqLJQDwHF6Kr4S-x-eG7ikClwYqcJ85A1VLsuhWQR9JKihs_Tg-ozERklUCOYmmO1Aj-bw3ED0KSODJPcJN3gBfbYsNGgeRNt89DyhzPt3yPNie0Vzyp2e_ZFqsnZEQ0o9l5sqNK0z2SY7v6XaEU-4T690WBQCAPObVTlgO2-DcBUsuk_ul2WuLm4bCAQoUWeRUz5aiwb-DD_c8T0xWsSbjj7Q_hZZCwCc_J-5pCPrgyYI0UWankIxQXBg_mS6Frum_P6T7-mp82JM0QtaeN33uscGQ6nyctMTihHe4sN9i5F2v93bMQ7fjq8otWVfSAOAgsL4_krI-HeZ--hmg5AKvK4UKYUQ0i4oTou7yzFYAXcoLQ1kVfqB4giR26pB9fntU4B6FDDFrC1RTq4g4KHrhaJo4Kg5RiFa9RRhN0sEBbanDVfF6is15JwIVpyxXl2oJ30LiKgVAdS1ohDfMdOC3R7U69ueLEJEubRQu-p5FGGGGV1C5GCwf-iOb8eU-6X_j6UiXz2Rud9ettGtCMRLrbJCoeEGY0Eh0tCoI0jL7ErXdblSz3pEoD5g=w932-h932-s-no-gm?authuser=0",
        description = "\uD83D\uDD2E Traga a magia de The Witcher para sua casa com este incrível action figure do Bruxo, interpretado pelo talentoso Henry Cavill! Criado com detalhes impressionantes e uma qualidade excepcional, este action figure é uma homenagem perfeita à icônica série. Com sua postura imponente e olhar penetrante, ele irradia poder e mistério. Uma adição indispensável à coleção de qualquer fã, este action figure é uma obra-prima de arte e um tesouro para ser exibido com orgulho. Traga a aventura e o encanto de The Witcher para sua vida com este action figure do Bruxo! ✨\uD83D\uDDE1\uFE0F\uD83C\uDF0C"
    ),
    Product(
        name = "Son Goku Super Saiyajin",
        price = BigDecimal("200.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV84n7uEyXPp6HxguSxjzGxlvJ4kGYc57amS027FJdYIk8TIwtGsk0i_ZuTADi1JDjgqEG5koqOf06GBD7Ue81sM-3zIliDxdZpd3Bp5z6-pfdZ5Fipp_7WUJ2eK3WrV_TJBBLQ7NrATU3pYWRVWHC1StCC1lWneOQv-ZbXYvXMpgrft1pWAaxq-5F7HVy53GBSnhsSJnz2-R0EidhTKsQdWOFngPtibxr2oYHvqLo0DHAUjC_Oizt7y-MTXdvZIoyULCDX3t1kBiTi2cCaZLSnldVUk0gk6p8JfclFDLRwv7S_ltNQFIuHYqer0RCOlKGyLfICRAojs_ok7GnPuGB6oonk0K6s0bNVNZN9jvpfphuLlFEyfsTh5mHgKnVCEG-BsD4_BI_AUGPQBmgtQo0O7dXdZM8bxRjomaMx3K9wmeUWQxqYHAU3esVlxZZBQ5qhVtxnbOKCEps4WxNsPl5ksvYF3NSw86o46EKkuAsS-C5OC6LWiypA0UA_i3hMJHJ-XGsnB7lkYNCCbQ6Tastme0qRv_eR_JXlL6fR2G8b2w7HHF0ja90rnLBLoSLUGQvZa4Swg-vemDLkmMpCvnmASbiplYYrgIAETmtAJIbDABzzu-40lAmhYQNEdJgUC_3DJQdL9AN-4eqVVjSI0qwTp3OkY7DK0uH-uG6J5Ti-iUDdXvLxOcAgpx2m69KEpComevcqR_h5hx3Q5x_Jj0J7VTzuM_a05enG1e_SZgzZpKhBM1EPekb_qObHDMDXaKygjt3iAG6S-bMWMJDlPWwSoHQBvpcJI3pvmHEVTtP4amyrS2Beob1ocBG95oSo2frIM5tSaMSQHcykjmTuK7f-OSkRGrdq-Zc5Gs1hI2g4N8Olsxavg1472U42OONHuN2eLDp-zLexK-STfGUzo-Rmpogkw=w826-h932-s-no-gm?authuser=0",
        description = "\uD83D\uDC09⚡ Entre no mundo da poderosa série Dragon Ball Z com este incrível action figure do Goku Super Saiyajin, com o lendário Shenlong envolto em sua aura!. Com detalhes impressionantes e cores vibrantes, este action figure captura a essência da série de anime amada por milhões em todo o mundo. A presença majestosa de Shenlong adiciona um toque de magia e mistério, tornando este action figure uma peça verdadeiramente única e impressionante. Seja você um fã ávido de Dragon Ball ou um colecionador de action figures, esta peça é um tesouro imperdível que irá iluminar sua coleção e destacar sua paixão pelo universo de Dragon Ball! \uD83D\uDC32\uD83D\uDCA5\uD83C\uDF1F"
    ),
    Product(
        name = "Busto Batman Michael Keaton",
        price = BigDecimal("80.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV85BZNkoBNUBqQ6fg8VGNzTCrY42SCG-6wgwhxI_1G6rouyfQoHFahHm_EyGpCaMqvXO_9gMIRbf_u-Ia_87xe7KpoDF_SJkxNGZvMh6fKnAvWolBnghNr_ekThJb9z5fIS5bnDBCwUB0NFRuR4tYlCK8t5A4JJJz-_uImVjt85XZ7XZ7PAZa4h7Yk3rjr1ykKfJgVk6tezaO9H02fKiHAPm7REkGeAnncd93N9c-1Edt8wqSMcuR5VKh6t4RD-nkf6zK-HeDlTN7GZO7mChSaM1j-nYgpb5fDLI84Tx2sp0AIIFymSosKaO0plbfixMSIM7LKiG_YiaAwQMDvEv0sBk0LC4ezff0nsllCfC1NmozqSGXczjARtrMHLRAPnQg1LRJ6iedjg2zRlNS8gB4JIfUglqet9unQdI_X1O6yl6nwyQMJ4n6j3TM1EdugUAa5KDYCgs-FGic2cdKBmmeB0Scvc30_T6LfMVU6jBYYFmt_x7G9DuW88OQuOYvSx6GY3YBJ4XWw8zjIBxeYIHrGHNDa3wv2xZqc2ehrkaEvo9M-kFI37dmz9lCRAJkpnthoA_lmZ4fw9k3vtXwbYcQdVHCp-4Z-7XsZ0zFrPllbD7-ec2NSO61j2e2cJykmZ1BJxlz8KeHE_XlfceMUzSuQA-zIAtJ9D7iy86RPSGT6D6EHOEFDKwvYmAUiSg90RnkIb09076yqQVSUvVAF9spTAxTdy1irP0uFMqCbPfIDNwoUKor5zISqmJo-8TOxd35vMxd60nSqRu3hKV1yok8GjHTXKjM7XQCrJuLfn-YkQKuEUf5vIJO3OB8MifBKasBUZk5M0gYG9a68tEiuXq_XPnlOabxirgDSreNo-qYOGc2R4hXPjXZA3gQJ6FsdAeUF48UIWkjXUmAyt053aQNhgReWI=w932-h932-s-no-gm?authuser=0",
        description = "\uD83E\uDD87 Torne-se o defensor da justiça com este busto incrível do Batman, imortalizando a lendária interpretação de Michael Keaton! Feito com precisão em uma impressora 3D de alta qualidade, este busto captura a essência do Cavaleiro das Trevas e adiciona um toque de elegância e mistério a qualquer ambiente. Perfeito para fãs de super-heróis e colecionadores de arte, esta peça será o destaque da sua coleção. Adicione um toque de heroísmo à sua vida e leve para casa este épico busto do Batman hoje mesmo! \uD83C\uDF1F\uD83E\uDD87\uD83D\uDCA5"
    )
)

val sampleSports = listOf(
    Product(
        name = "Benny Mascote do Chicago Bulls",
        price = BigDecimal("100.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV85Q6m5wqhMfFs6XcvzxofQxNQpzu96ZxvN0H3yuJtv21dkkFYM23BkSf3xwBxPUMm3jCeWim0jPJ2aEdG4au71NC_2u3HUW2qmT9KWVbh5RrO1FkiK9ITQsDkqf5SGgVAVRaYgUPJMybfpRCwE8tZiVU-07NxLvNq6kHD1nE7NdfHOg2CISPOJY6Fetx--rrZtXhsUKWF5UD-zRGbMkw2RKZabXLdWoyDwNWa5idA8IMDqi5OdH4Voq_qPVrseof0CJDV-_dOXsb9DooILqZ9WOqiwDVri9fNC1ZGvLmwvmHWoflCy6FSSQNr3MwPx0BSdOp3qPre3W04Yti5GXtkAROyy_tezzVsLWD1mYEimZMxMOZ4dnafoUJbA8Atv6k1iBynBI1PLuxZrZiXR9WSBA-nBU3y6bL6hmREr6S0Qi1wFehGn8ZhZ4P5qqoVpexau1Wu_H0l6R4EIHXxu9zGKrQDJchZBOcOH-TLIHZiyfUzcYZze1XivtIyMNfbsXtTETXBwSR8ccMe2YgXqrbQncZixCa5AE34V7VRb63G2Lh9CQikbd8D0yX4CWZJqbGUVhUKtEUMt5YPEjyhl8E0Nt22F17zAElbVzIJYzOAV2Ywg6U4zZ2VT5QUI3jFRhGVpeVlbVaoKzj0Vky_HrmnL1kuYwGglMZjbB4xywOznY84r-1WrAzKaVxrsXa2HCzyN8ZCmu8RRja3O1Pi3_cO-4d2xVVoRlf1IT3NsKKPVCA8WBaZtEP6ghumZFMz9vhXKbC_BSL1jo4ahz3TRsJ1cuoVjY764Km9w0eo7Z0hT1H4nHS1Vm5SvZaFO8WnR_Yv_koBIjXEDcs47C3rM7llLVI6UEy7WbqQ6x0MLeA23wHmYXXJf7sA5qH-zXyKxh_w3UpDtACB6rd9R5YnzQMG_xq4M=w932-h932-s-no-gm?authuser=0",
        description = "🏀 Apresentando uma peça impressa em 3D do mascote do icônico time de basquete Chicago Bulls. Esta obra de arte, meticulosamente detalhada, é um tesouro para qualquer fã do Bulls. 🎉 Criada com material resistente de alta qualidade, é ideal para adicionar um toque esportivo à sua casa ou escritório. 🏠 Exiba seu amor pelo time com esta peça impressionante! 💪"
    ),
    Product(
        name = "Mascote do Golden State Warriors",
        price = BigDecimal("100.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV878-44zHVgiM1tVbn7R1TTCXETatEu5QTTCLEmilPAQWIdjlkcVR4yI3DoDdIMPf7h9Zo6hJj8ZFKSVcSGzEYfGKWy1-q0na06-xso6AHSYz8GcLmhIUzNUxPbZZQ51RXfS9E4dr0vdxE9xLCCSCfMDy0mneqCqQbz0XYdiZJQOuRrNN0wUNTVHMR9WKLSRwNy5hwMr0bVKzNa3Pg0ifWCvJAKw2G1IZLOFaplOeOhlsyNgvRD7LXKGSQDRBvra_x-CaRDW48lefSFmqgjKRWRevj-RDiPZ-61rk5lBhK-y97VPPF_o4T3O3kendqg2DlGdQfQuLnjpwXxl9z5UCOdwru3TfaMeoh2i-C1XBBA4VETHEiPyDcesnk46fXrlTQcUMgW4l1RV1iUy7vqzh7w5DThvQEBZEoeHtGtaTi7mLR_jSbN9rylMDlGJKQQ31hCgQdWMqJGLZMS0rRsiD9PPLOhNOsN6NfrplMPhxHyoxhZZp3dSsQVUtbpNOrgRjKzJt_fEVLYAEscGcdrJTryBERjAUUYmOcKMghkAfDc6ou1iP9hWIPoHXM2Jl3vLu_umcfkBtHjC8BToR2a2i_lCSbW-Ob0uqD7-FgEdbvznAnbmTxoe93L_TBttS0pnDJGeLyXTzkq7yOgAUz84Ot33isY_njYPPlXe9iYjYbGrGQtIg7rUIEJbKS4OJMEuPks1yt4IPatlK2cftJlWqdP7E9p56gnDLq2cYdI598IPvUKfwT8SLurUI56cooidIdEWxKgGT_y4FzInzBRcgY3c2z6n8ul88lGi-Cq1xGBc8o3nxMFqXyuYN_jVofkASMqEfT99cYZ2ifwaWnR3XhwacrAosg7C6IqVq2pPgk-MnOeFMDUsXHOnm1rBk3A-fNZJP0TuCEGUeHZlHHgTlG_29WQ=w932-h932-s-no-gm?authuser=0",
        description = "\uD83C\uDFC0 Peça exclusiva impressa em 3D do mascote do renomado time de basquete Golden State Warriors. Esta peça única, rica em detalhes e precisão, é um item indispensável para qualquer fã do Warriors. Feita com material durável de alta qualidade, ela é perfeita para exibir em sua casa ou escritório. \uD83C\uDFE0 Mostre seu espírito de equipe com orgulho! \uD83D\uDCAA"
    ),
    Product(
        name = "Cristiano Ronaldo do Real Madrid",
        price = BigDecimal("70.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV87xYvYHP6gm4WxPYGxywnGj4tZqCJgU0u1z0oHXpiB5XPfPsldRB-ouzktC5ab-vVIhmLM9NQDFxL0bA7_jhxKLW_41peG09NtpchM-APQUjzmlK1DKvwEPJ7v12xeQYASQxQyLptV9voF0-Dk2xeXbkcCW7qgEP86wnX8qd5tyEacd5IPbjwLZ8xUv6n4xweK8YytsJHXRkWD5S3BFjqDLm8EqL6F-0Ty9_2e40baW_WO-wUcSyX8NQ9Q-afqkDtlsBM0yErLlmn6h1j0gzbYvlrCKQMelTZhOlqh9vVPFgMyYM36e8DZ2AenQYuwcaT4lGUzoyUuO7gVwFWLFLWQV9C4-IYWmw5f-WIUIVwvInHmwN0bKah7b1iXx8PtX2MCBcK_ma3clp7Qnsmwa-knzTY40IgCCJyRJpRwil5jSQtk7NuYluQPTwcOX3N3UBaDqyfxD1wNm9Eefb3uwUujQrsD1kVGdGxEt39n1mjLYUf5Hgy9wzX_ah6JbyzgOyj59_qfBTihJGWbaglxilgLw70EICi2vGjExDfhz9m7KKB11AD8QzxVrX8TH3U0tPquG6Fs01gsUZmkvpv8OdvqR02SVuTDw5zCuKkPm6TnFHrwHO8k4BySYq0eBXWxYu6QUivJxsI6ibqzT57jiNEMee73ARXoxxwVaBh1uIKGxM0Ec7Pfc79HSulcvTneW26aANCoYBM0p_iTatsui8OXIwuEuPX75jgoqJo_8yjCdscbz1S-97ZPA2XaKaJFGsh7Ivw_6HBblJKMO7JZwah_KRq9vi8X7MxqheBhmnFCm2nZofdTMlJlx8_3fA_JDZvE5JzEQUOJdfeuLWj9QuZQE81LssO_BoSSW3U6ckOQ1QEELFfbjfk2MD9zC2j4jC93qhdIPkYMa0Ybn9o2xz3aduFE=w932-h932-s-no-gm?authuser=0",
        description = "⚽ Entre em campo com esta incrível peça que celebra um dos momentos mais icônicos do futebol: a épica comemoração de gol de Cristiano Ronaldo pelo Real Madrid! Este action figure captura a intensidade e a emoção do momento em que Ronaldo abre os braços em triunfo após mais uma jogada fenomenal. Se você é um fã de futebol apaixonado ou um admirador do lendário Cristiano Ronaldo, esta peça é uma adição essencial à sua coleção. Reviva a emoção dos momentos mais memoráveis do futebol com este action figure que celebra a grandeza de um dos maiores jogadores de todos os tempos! \uD83C\uDFDF\uFE0F 9\uFE0F⃣ \uD83C\uDF1F"
    ),
    Product(
        name = "Mosqueteiro Mascote do time Crinthians",
        price = BigDecimal("70.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV84seVG-eP0h9cs69dJ_n2l23psN3wkcgnbiuR0T7nkNnX2IhDl6Vn3-OVxj_8gYvgU5Jb3IQr1Fk-8QBajoiPvdffJDgWOLEDDjv25OhN5Cgh8MbNJ2qHOocCl8aLTvhhR6FsmVabIJAHdxku-uXsulMEERGutXkqHiEhZGzqs4i7uWiC_Ub47yEhdO7XKEMyNM-4xhVcjkFBbBwAT8OKAb-ZLQqZzvGGT0q1deJA4gAknLo18-P1ZlHIgxWPT_jOSEAdLcYlUTQPBPeMG4QXHYUIM8DTCREG923rgr5hyM2ETWBfufMyLT-feJvyhuVPrBy_RxqzO-0W1T1XwG-mtZV6x0tGm5WCI4I5Y7xd19OAHAV-eVTu4nanDKztnUeXVWuZ6f8Sq5ZQ9O8AI3z9gfQAN0UjgwH7TG7pNPsSHaPE6CkLGpxT7FgTZOLrprZ0xwdYdDTLwlL87YDsQ_NUAeo1Ly-aw4XjjA57P2sxawRpWwuxDJGZVnrqKcUR0DMVZtYy2auRLpP3hBWNzaRmgaNj-kmOYmZBZNa0SadaE5xfDMQAZV51bZmYe-gqMtPvlCzx9PxPmniuRaHzV-ZJVGM6bbybPyFWm17UxrfgYVgexTjNowDva7sC6V0MPq9kMMxQO1bc8PC6QXStbqcHT9EKfyrHyy2WMj4QQSif6GfcylLbAC94LhdZFBXkSmGfCaC6H96sFFiRoZxgUpa2Vo-6O_hr_uf_8u2IctaXEub9dDFLP4n-7mU2zpl_-WmcfsjzeE4c_muqgiJj4bUrkjh6K_HHICfyuERGHbw0zmI08TQ0_2aJcYtuewQsmsjeC9Fvqi91nMTdAY-7YEXERuUtMazTN6Lp9mRD8q4jpicNtK4wFf6ONu8YPNQLM9vbFBxmTDIgMurOBqHKVcA0ft9A=w932-h932-s-no-gm?authuser=0",
        description = "⚓ Celebre a paixão pelo Corinthians com o mascote mais carismático! Este incrível action figure traz o Mosqueteiro, símbolo icônico do Corinthians, em toda a sua glória tridimensional. Com detalhes impressionantes e uma pose marcante, esta peça é um tributo à história e à tradição do clube. Perfeito para os fãs mais devotos, esta figura é uma maneira perfeita de mostrar seu apoio ao Timão em grande estilo! ⚽\uD83D\uDD25\uD83D\uDC51"
    )
)

val sampleNewProducts: List<Product> = listOf(
    Product(
        name = "Mascote do Golden State Warriors",
        price = BigDecimal("100.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV878-44zHVgiM1tVbn7R1TTCXETatEu5QTTCLEmilPAQWIdjlkcVR4yI3DoDdIMPf7h9Zo6hJj8ZFKSVcSGzEYfGKWy1-q0na06-xso6AHSYz8GcLmhIUzNUxPbZZQ51RXfS9E4dr0vdxE9xLCCSCfMDy0mneqCqQbz0XYdiZJQOuRrNN0wUNTVHMR9WKLSRwNy5hwMr0bVKzNa3Pg0ifWCvJAKw2G1IZLOFaplOeOhlsyNgvRD7LXKGSQDRBvra_x-CaRDW48lefSFmqgjKRWRevj-RDiPZ-61rk5lBhK-y97VPPF_o4T3O3kendqg2DlGdQfQuLnjpwXxl9z5UCOdwru3TfaMeoh2i-C1XBBA4VETHEiPyDcesnk46fXrlTQcUMgW4l1RV1iUy7vqzh7w5DThvQEBZEoeHtGtaTi7mLR_jSbN9rylMDlGJKQQ31hCgQdWMqJGLZMS0rRsiD9PPLOhNOsN6NfrplMPhxHyoxhZZp3dSsQVUtbpNOrgRjKzJt_fEVLYAEscGcdrJTryBERjAUUYmOcKMghkAfDc6ou1iP9hWIPoHXM2Jl3vLu_umcfkBtHjC8BToR2a2i_lCSbW-Ob0uqD7-FgEdbvznAnbmTxoe93L_TBttS0pnDJGeLyXTzkq7yOgAUz84Ot33isY_njYPPlXe9iYjYbGrGQtIg7rUIEJbKS4OJMEuPks1yt4IPatlK2cftJlWqdP7E9p56gnDLq2cYdI598IPvUKfwT8SLurUI56cooidIdEWxKgGT_y4FzInzBRcgY3c2z6n8ul88lGi-Cq1xGBc8o3nxMFqXyuYN_jVofkASMqEfT99cYZ2ifwaWnR3XhwacrAosg7C6IqVq2pPgk-MnOeFMDUsXHOnm1rBk3A-fNZJP0TuCEGUeHZlHHgTlG_29WQ=w932-h932-s-no-gm?authuser=0",
        description = "\uD83C\uDFC0 Peça exclusiva impressa em 3D do mascote do renomado time de basquete Golden State Warriors. Esta peça única, rica em detalhes e precisão, é um item indispensável para qualquer fã do Warriors. Feita com material durável de alta qualidade, ela é perfeita para exibir em sua casa ou escritório. \uD83C\uDFE0 Mostre seu espírito de equipe com orgulho! \uD83D\uDCAA"
    ),
    Product(
        name = "Mascote do Chicago Bulls",
        price = BigDecimal("100.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV85Q6m5wqhMfFs6XcvzxofQxNQpzu96ZxvN0H3yuJtv21dkkFYM23BkSf3xwBxPUMm3jCeWim0jPJ2aEdG4au71NC_2u3HUW2qmT9KWVbh5RrO1FkiK9ITQsDkqf5SGgVAVRaYgUPJMybfpRCwE8tZiVU-07NxLvNq6kHD1nE7NdfHOg2CISPOJY6Fetx--rrZtXhsUKWF5UD-zRGbMkw2RKZabXLdWoyDwNWa5idA8IMDqi5OdH4Voq_qPVrseof0CJDV-_dOXsb9DooILqZ9WOqiwDVri9fNC1ZGvLmwvmHWoflCy6FSSQNr3MwPx0BSdOp3qPre3W04Yti5GXtkAROyy_tezzVsLWD1mYEimZMxMOZ4dnafoUJbA8Atv6k1iBynBI1PLuxZrZiXR9WSBA-nBU3y6bL6hmREr6S0Qi1wFehGn8ZhZ4P5qqoVpexau1Wu_H0l6R4EIHXxu9zGKrQDJchZBOcOH-TLIHZiyfUzcYZze1XivtIyMNfbsXtTETXBwSR8ccMe2YgXqrbQncZixCa5AE34V7VRb63G2Lh9CQikbd8D0yX4CWZJqbGUVhUKtEUMt5YPEjyhl8E0Nt22F17zAElbVzIJYzOAV2Ywg6U4zZ2VT5QUI3jFRhGVpeVlbVaoKzj0Vky_HrmnL1kuYwGglMZjbB4xywOznY84r-1WrAzKaVxrsXa2HCzyN8ZCmu8RRja3O1Pi3_cO-4d2xVVoRlf1IT3NsKKPVCA8WBaZtEP6ghumZFMz9vhXKbC_BSL1jo4ahz3TRsJ1cuoVjY764Km9w0eo7Z0hT1H4nHS1Vm5SvZaFO8WnR_Yv_koBIjXEDcs47C3rM7llLVI6UEy7WbqQ6x0MLeA23wHmYXXJf7sA5qH-zXyKxh_w3UpDtACB6rd9R5YnzQMG_xq4M=w932-h932-s-no-gm?authuser=0",
        description = "🏀 Apresentando uma peça impressa em 3D do mascote do icônico time de basquete Chicago Bulls. Esta obra de arte, meticulosamente detalhada, é um tesouro para qualquer fã do Bulls. 🎉 Criada com material resistente de alta qualidade, é ideal para adicionar um toque esportivo à sua casa ou escritório. 🏠 Exiba seu amor pelo time com esta peça impressionante! 💪"
    ),
    Product(
        name = "Busto Batman Michael Keaton",
        price = BigDecimal("80.00"),
        image = "https://lh3.googleusercontent.com/pw/ABLVV85BZNkoBNUBqQ6fg8VGNzTCrY42SCG-6wgwhxI_1G6rouyfQoHFahHm_EyGpCaMqvXO_9gMIRbf_u-Ia_87xe7KpoDF_SJkxNGZvMh6fKnAvWolBnghNr_ekThJb9z5fIS5bnDBCwUB0NFRuR4tYlCK8t5A4JJJz-_uImVjt85XZ7XZ7PAZa4h7Yk3rjr1ykKfJgVk6tezaO9H02fKiHAPm7REkGeAnncd93N9c-1Edt8wqSMcuR5VKh6t4RD-nkf6zK-HeDlTN7GZO7mChSaM1j-nYgpb5fDLI84Tx2sp0AIIFymSosKaO0plbfixMSIM7LKiG_YiaAwQMDvEv0sBk0LC4ezff0nsllCfC1NmozqSGXczjARtrMHLRAPnQg1LRJ6iedjg2zRlNS8gB4JIfUglqet9unQdI_X1O6yl6nwyQMJ4n6j3TM1EdugUAa5KDYCgs-FGic2cdKBmmeB0Scvc30_T6LfMVU6jBYYFmt_x7G9DuW88OQuOYvSx6GY3YBJ4XWw8zjIBxeYIHrGHNDa3wv2xZqc2ehrkaEvo9M-kFI37dmz9lCRAJkpnthoA_lmZ4fw9k3vtXwbYcQdVHCp-4Z-7XsZ0zFrPllbD7-ec2NSO61j2e2cJykmZ1BJxlz8KeHE_XlfceMUzSuQA-zIAtJ9D7iy86RPSGT6D6EHOEFDKwvYmAUiSg90RnkIb09076yqQVSUvVAF9spTAxTdy1irP0uFMqCbPfIDNwoUKor5zISqmJo-8TOxd35vMxd60nSqRu3hKV1yok8GjHTXKjM7XQCrJuLfn-YkQKuEUf5vIJO3OB8MifBKasBUZk5M0gYG9a68tEiuXq_XPnlOabxirgDSreNo-qYOGc2R4hXPjXZA3gQJ6FsdAeUF48UIWkjXUmAyt053aQNhgReWI=w932-h932-s-no-gm?authuser=0",
        description = "\uD83E\uDD87 Torne-se o defensor da justiça com este busto incrível do Batman, imortalizando a lendária interpretação de Michael Keaton! Feito com precisão em uma impressora 3D de alta qualidade, este busto captura a essência do Cavaleiro das Trevas e adiciona um toque de elegância e mistério a qualquer ambiente. Perfeito para fãs de super-heróis e colecionadores de arte, esta peça será o destaque da sua coleção. Adicione um toque de heroísmo à sua vida e leve para casa este épico busto do Batman hoje mesmo! \uD83C\uDF1F\uD83E\uDD87\uD83D\uDCA5"
    )
)

val sampleProducts = listOf(
    *sampleSports.toTypedArray(), *sampleHeros.toTypedArray()
)

val sampleSections = mapOf(
    "Novidades" to sampleNewProducts,
    "Herois" to sampleHeros,
    "Esporte" to sampleSports
)